# Generated by Django 4.2.4 on 2023-11-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('asistencia', models.CharField(max_length=20)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actividades.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.PositiveIntegerField()),
                ('actividades', models.ManyToManyField(through='Entrenadores.Clase', to='Actividades.actividad')),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenadores.entrenador'),
        ),
    ]
