# Generated by Django 4.2.4 on 2023-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='asistencia',
            field=models.CharField(blank=True, default='sin registro', max_length=20, null=True),
        ),
    ]
