# Generated by Django 4.2.2 on 2023-11-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0003_alter_actividad_options'),
        ('Entrenadores', '0002_alter_clase_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='entrenador',
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='actividades',
            field=models.ManyToManyField(to='Actividades.actividad'),
        ),
    ]
