# Generated by Django 4.2.4 on 2023-11-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='importe',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
