# Generated by Django 4.2.4 on 2023-12-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0004_alter_alumno_actividades_alter_alumno_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='alumno',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='Alumnos.alumno'),
        ),
    ]
