# Generated by Django 4.2.4 on 2023-12-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0005_alter_cuota_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Alumnos.plan'),
        ),
    ]
