# Generated by Django 4.2.4 on 2023-12-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0006_alter_alumno_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['importe']},
        ),
    ]
