# Generated by Django 4.2.4 on 2023-12-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0007_alter_plan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='choice_cuota',
            field=models.CharField(choices=[('impago', 'Adeuda cuota'), ('pago', 'Al día')], default='impago', max_length=10),
        ),
    ]
