# Generated by Django 4.2.2 on 2023-11-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrenadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('asistencia', models.CharField(default='Sin registro', max_length=30)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Actividades.actividad')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='dia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actividades.dia'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='entrenadores',
            field=models.ManyToManyField(to='Entrenadores.entrenador'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actividades.horario'),
        ),
    ]
