# Generated by Django 4.2.2 on 2023-11-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0002_alter_actividad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['id']},
        ),
    ]
